[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$rFUqBcCYM6a0ltL6H8P4fw$eWEXoO8DrUonL3OBmCRULEpjD6/NASUe5KpBlrsdvfZGDrkT1LZFlTBVT.XL0bvWU2AybzAvDcgoaEFmkZuo5Q
db_host = odoo-postgres
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo_development